### PR TITLE
remove trailing whitespace

### LINKED ISSUE #1: A reference: How to remove trailing space
I just figure out how to remove trailing spaces like tabify insert spaces for indent, [commit](https://github.com/racket-tw/sauron/commit/769cb7e318e03da895a0564b5c72fff36e8fb67d) reference for you, that will be great if the formatter can handle more.

### PR DESCRIPTION
**Pull request by dannypsnl**
resolve #1

### CODE REVIEW

**Comment by mxork** [comment]
Thanks for the PR! This is a good feature, and I would probably make it the default.  

However `remove-whitespace%` will trim trailing space from the end of multiline string literals. For example,

```
(define a-long-string "
apple          
toad    
")
```

Becomes:

```
(define a-long-string "
aplle
toad
")
```

Which is a blocker (a formatter shouldn't make an observable change to a program). With a patch, and, ideally, a test case, I will merge.

Again, thanks for the code!

**Comment by dannypsnl** [comment]
resolved, you can check new test case

**Comment by mxork** [comment]
Thanks for the followup. Unfortunately, the method does not work as intended. I've attached an input file, the generated output, and the expected output.

[expected.txt](https://github.com/mxork/raco-format/files/6743315/expected.txt)
[input.txt](https://github.com/mxork/raco-format/files/6743316/input.txt)
[output.txt](https://github.com/mxork/raco-format/files/6743317/output.txt)

**Comment by dannypsnl** [comment]
You can check this version, this time I open skip when meet first `"` and close skip line when meet second `"`, this shall work.

**Comment by dannypsnl** [comment]
Any updates here?

**Comment by mxork** [comment]
When I run latest on `input.txt`, the whitespace inside of the string literal is still trimmed. Let me know if this is not the case when you run it.

You might want to consider using racket's `read` when you encounter a string literal to determine how far to skip.

**Comment by dannypsnl** [comment]
Oops, I guess I find the reason, it only works for the string like:
```rkt
"
this
"
```
but not
```rkt
 "
this
"
```

**Comment by dannypsnl** [comment]
just updated, hope this test case covering enough cases.

**Pull request closed without merging**
